name: temoa-py3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.3
    - pyomo=5.5
    - pyomo.extras
    - xlwt
    - ipython
    - matplotlib
    - pandas
    - numpy
    - scipy
    - joblib
    - salib
    - pydoe
    - pyutilib
    - glpk
    - coincbc
    - appdirs=1.4.3
    - asgiref=3.2.3
    - backcall=0.1.0
    - cycler=0.10.0
    - decorator=4.4.1
    - Django=3.0.3
    - ipython=7.11.1
    - jedi=0.15.2
    - kiwisolver=1.1.0
    - nose=1.3.7
    - parso=0.5.2
    - pexpect=4.7.0
    - pickleshare=0.7.5
    - ply=3.11
    - ptyprocess=0.6.0
    - Pygments=2.5.2
    - pyparsing=2.4.6
    - python-dateutil=2.8.1
    - pytz=2019.3
    - six=1.13.0
    - sqlparse=0.3.0
    - traitlets=4.3.3
    - wcwidth=0.1.8
    - xlrd=1.2.0
    - xlutils=2.0.0
    - python-dotenv
    - psycopg2
    - Django=3.0.3
    - matplotlib=3.1.2
    - numpy
    - pandas=0.25.3
    - PyUtilib=5.7.3
    - scipy=1.4.1
    - python-dotenv
    - psycopg2
    - gunicorn
