# Generated by Django 3.0.3 on 2020-04-06 11:12

import dapp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=500)),
                ('mode', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output'), ('Model', 'Model')], default='INPUT', max_length=10)),
                ('desc', models.TextField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Actions')),
            ],
        ),
        migrations.CreateModel(
            name='InputOutputDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('file', models.FileField(max_length=500, upload_to=dapp.models.io_upload_file_to)),
                ('mode', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output'), ('Model', 'Model')], default='INPUT', max_length=10)),
                ('name', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Actions')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('create_spreadsheet', models.BooleanField(null=True)),
                ('create_text_file_output', models.BooleanField(null=True)),
                ('generate_lp_file', models.BooleanField(null=True)),
                ('solver', models.CharField(max_length=50)),
                ('run_option', models.CharField(max_length=20, null=True)),
                ('mga_slack_value', models.CharField(max_length=20, null=True)),
                ('mga_iterations', models.CharField(max_length=20, null=True)),
                ('mga_weighting_method', models.CharField(max_length=20, null=True)),
                ('scenario_name', models.CharField(max_length=100, null=True)),
                ('custom_flags', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Actions')),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='dapp.InputOutputDataFile')),
                ('output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='dapp.InputOutputDataFile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='OutputDataRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('color_scheme', models.CharField(max_length=20)),
                ('output_format', models.CharField(max_length=20)),
                ('sectors', models.CharField(max_length=50, null=True)),
                ('plot_type', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(help_text='Use the following format: <YYYY>', max_length=20, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)])),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Actions')),
                ('comm_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp.CommTech')),
                ('input_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp.InputOutputDataFile')),
                ('model_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp.ModelRun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='modelrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario'),
        ),
        migrations.AddField(
            model_name='inputoutputdatafile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project'),
        ),
        migrations.AddField(
            model_name='inputoutputdatafile',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario'),
        ),
        migrations.CreateModel(
            name='InputDataRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('color_scheme', models.CharField(max_length=50)),
                ('output_format', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Actions')),
                ('comm_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.CommTech')),
                ('input_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp.InputOutputDataFile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('file', models.FileField(max_length=500, upload_to=dapp.models.upload_file_to)),
                ('name', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='commtech',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project'),
        ),
        migrations.AddField(
            model_name='commtech',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario'),
        ),
        migrations.AddField(
            model_name='actions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Project'),
        ),
        migrations.AddField(
            model_name='actions',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.Scenario'),
        ),
    ]
