# Generated by Django 3.0.3 on 2021-07-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputplot',
            name='input_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp.InputOutputDataFile'),
        ),
    ]
