# Generated by Django 3.0.3 on 2020-04-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_modelrun_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrun',
            old_name='server',
            new_name='neos_server',
        ),
    ]
